import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/nav/navbar";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en">
    <body
      className={cn("relative h-full font-sans antialiased", inter.className)}
    >
      <main className="relative flex min-h-screen flex-col">
        <Navbar />
        <div className="flex-1 flex-grow">{children}</div>
      </main>
    </body>
  </html>
);

export default RootLayout;
